# -*- coding: utf-8 -*-
"""Uzma_lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lydEGoI_vPLYYal4nCN8JCoS7-PPTrXe
"""

!pip install -U google-genai
from google import genai
client = genai.Client(api_key="AQ.Ab8RN6KZXKLh4fksbf6t2Zg3jgYOBq72cFafib1w0FWce4aJiA")
MODEL = "models/gemini-3.6-flash"

response = client.models.generate_content(
    model="models/gemini-3.6-flash",
    contents="Hello"
)
print(response.text)

!pip install -U google-genai
from google import genai

client = genai.Client(api_key="AQ.Ab8RN6KZXKLh4fksbf6t2Zg3jgYOBq72cFafib1w0FWce4aJiA")

print("Gemini Chatbot (type 'exit' to quit)\n")

while True:
    user_input = input("You: ")

    if user_input.lower() in ["exit", "quit", "bye"]:
        print("Chatbot: Goodbye 👋")
        break

    response = client.models.generate_content(
        model="models/gemini-3.6-flash",
        contents=user_input
    )

    print("Chatbot:", response.text)